server:
  port: 8201
spring:
  application:
    name: service-acl
  cloud:
    nacos:
      discovery:
        server-addr: 123.60.218.173:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.60.218.173:3306/mybatis?serverTimezone=GMT%2B8
    username: root
    password: 1234
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    database: 0
    host: 123.60.218.173
    port: 6379
    lettuce:
      pool:
        max-active: 20
        max-idle: 5
        max-wait: -1
        min-idle: 0
    timeout: 1800000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml